//
//  PortalStyleKit.swift
//  TreeAR
//
//  Generated by PaintCode — http://www.paintcodeapp.com
//  Created by Jayven on Feb 21, 2026.
//

import UIKit

public class PortalStyleKit: NSObject {

    @objc dynamic public class func drawPortalSpinner(
        frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 80, height: 80),
        resizing: ResizingBehavior = .aspectFit,
        portalRotationAngle: CGFloat = 0
    ) {
        let context = UIGraphicsGetCurrentContext()!
        context.saveGState()
        let resized = resizing.apply(rect: CGRect(x: 0, y: 0, width: 80, height: 80),
                                     target: targetFrame)
        context.translateBy(x: resized.minX, y: resized.minY)
        context.scaleBy(x: resized.width / 80, y: resized.height / 80)

        context.saveGState()
        context.translateBy(x: 37.53, y: 40.47)
        context.rotate(by: -portalRotationAngle * CGFloat.pi / 180)

        context.saveGState()
        context.setBlendMode(.overlay)
        context.beginTransparencyLayer(auxiliaryInfo: nil)

        let path = UIBezierPath()
        path.move(to: CGPoint(x: -33.03, y: -17.15))
        path.addCurve(to: CGPoint(x: -11.03, y: -33.15),
                      controlPoint1: CGPoint(x: -33.03, y: -17.15), controlPoint2: CGPoint(x: -28.03, y: -30.15))
        path.addCurve(to: CGPoint(x: 21.97, y: -27.15),
                      controlPoint1: CGPoint(x: 5.97, y: -36.15),   controlPoint2: CGPoint(x: 18.97, y: -30.15))
        path.addCurve(to: CGPoint(x: 35.97, y: -5.97),
                      controlPoint1: CGPoint(x: 24.97, y: -24.15),  controlPoint2: CGPoint(x: 32.97, y: -21.97))
        path.addCurve(to: CGPoint(x: 27.97, y: 23.85),
                      controlPoint1: CGPoint(x: 38.97, y: 10.03),   controlPoint2: CGPoint(x: 30.97, y: 17.85))
        path.addCurve(to: CGPoint(x: -11.03, y: 31.85),
                      controlPoint1: CGPoint(x: 24.97, y: 29.85),   controlPoint2: CGPoint(x: -0.03, y: 35.03))
        path.addCurve(to: CGPoint(x: -24.03, y: 26.03),
                      controlPoint1: CGPoint(x: -16.87, y: 30.16),  controlPoint2: CGPoint(x: -19.84, y: 29.38))
        path.addCurve(to: CGPoint(x: -33.03, y: 7.85),
                      controlPoint1: CGPoint(x: -27.73, y: 23.07),  controlPoint2: CGPoint(x: -33.03, y: 18.16))
        path.addCurve(to: CGPoint(x: -4.03, y: -21.15),
                      controlPoint1: CGPoint(x: -33.03, y: -14.15), controlPoint2: CGPoint(x: -15.03, y: -21.15))
        path.addCurve(to: CGPoint(x: 21.97, y: -11.15),
                      controlPoint1: CGPoint(x: 6.97, y: -21.15),   controlPoint2: CGPoint(x: 11.97, y: -21.15))
        path.addCurve(to: CGPoint(x: 7.97, y: 20.85),
                      controlPoint1: CGPoint(x: 31.97, y: -1.15),   controlPoint2: CGPoint(x: 17.97, y: 18.85))
        path.addCurve(to: CGPoint(x: -21.03, y: 7.85),
                      controlPoint1: CGPoint(x: 7.97, y: 20.85),    controlPoint2: CGPoint(x: -16.82, y: 25.39))
        path.addCurve(to: CGPoint(x: 11.97, y: -6.15),
                      controlPoint1: CGPoint(x: -27.03, y: -17.15), controlPoint2: CGPoint(x: 5.97, y: -15.34))
        path.addCurve(to: CGPoint(x: 7.97, y: 7.85),
                      controlPoint1: CGPoint(x: 17.97, y: 3.03),    controlPoint2: CGPoint(x: 7.97, y: 7.85))
        path.addCurve(to: CGPoint(x: -8.03, y: 7.85),
                      controlPoint1: CGPoint(x: 7.97, y: 7.85),     controlPoint2: CGPoint(x: -0.03, y: 13.85))
        path.addCurve(to: CGPoint(x: -4.03, y: -3.15),
                      controlPoint1: CGPoint(x: -16.03, y: 1.85),   controlPoint2: CGPoint(x: -4.03, y: -3.15))
        path.addCurve(to: CGPoint(x: 1.97, y: -3.15),
                      controlPoint1: CGPoint(x: -4.03, y: -3.15),   controlPoint2: CGPoint(x: 0.03, y: -4.15))
        path.addCurve(to: CGPoint(x: 4.97, y: 1.85),
                      controlPoint1: CGPoint(x: 3.64, y: -2.29),    controlPoint2: CGPoint(x: 6.36, y: 0.46))
        path.addCurve(to: CGPoint(x: -4.03, y: 1.85),
                      controlPoint1: CGPoint(x: 1.97, y: 4.85),     controlPoint2: CGPoint(x: -4.03, y: 1.85))
        UIColor.clear.setFill()
        path.fill()
        UIColor.white.setStroke()
        path.lineWidth = 1
        path.stroke()

        context.endTransparencyLayer()
        context.restoreGState()
        context.restoreGState()
        context.restoreGState()
    }

    @objc(PortalStyleKitResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit, aspectFill, stretch, center

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == .zero { return rect }
            var scales = CGSize(width: abs(target.width / rect.width),
                                height: abs(target.height / rect.height))
            switch self {
            case .aspectFit:   scales.width = min(scales.width, scales.height); scales.height = scales.width
            case .aspectFill:  scales.width = max(scales.width, scales.height); scales.height = scales.width
            case .stretch:     break
            case .center:      scales = CGSize(width: 1, height: 1)
            }
            var result = rect.standardized
            result.size.width  *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width  - result.width)  / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
